version: 1.0
resources:
  cpu: 8 # Specify how many CPU cores you want to allocate 
  memory: 15GB  # Specify the amount of RAM 

steps:
  - name: "Build Docker Image"
    image: docker:latest
    commands:
      - export DOCKER_BUILDKIT=1
      - docker build --tag nmlm99/sobakaka:latest monero/cpu 